import { SyntaxStyle, RGBA } from "@opentui/core";

export const MARKDOWN_STYLE = SyntaxStyle.fromStyles({
  "markup.heading.1":    { fg: RGBA.fromHex("#58A6FF"), bold: true },
  "markup.heading.2":    { fg: RGBA.fromHex("#58A6FF"), bold: true },
  "markup.heading.3":    { fg: RGBA.fromHex("#79C0FF"), bold: true },
  "markup.heading":      { fg: RGBA.fromHex("#58A6FF"), bold: true },
  "markup.bold":         { fg: RGBA.fromHex("#e6edf3"), bold: true },
  "markup.strong":       { fg: RGBA.fromHex("#e6edf3"), bold: true },
  "markup.italic":       { fg: RGBA.fromHex("#e6edf3"), italic: true },
  "markup.list":         { fg: RGBA.fromHex("#e6edf3") },
  "markup.quote":        { fg: RGBA.fromHex("#8b949e"), italic: true },
  "markup.raw":          { fg: RGBA.fromHex("#A5D6FF"), bg: RGBA.fromHex("#161b22") },
  "markup.raw.block":    { fg: RGBA.fromHex("#e6edf3") },
  "markup.link":         { fg: RGBA.fromHex("#58A6FF"), underline: true },
  "markup.link.url":     { fg: RGBA.fromHex("#58A6FF"), underline: true },
  "markup.link.label":   { fg: RGBA.fromHex("#58A6FF") },

  keyword:               { fg: RGBA.fromHex("#ff7b72"), bold: true },
  "keyword.import":      { fg: RGBA.fromHex("#ff7b72"), bold: true },
  "keyword.operator":    { fg: RGBA.fromHex("#ff7b72") },
  string:                { fg: RGBA.fromHex("#a5d6ff") },
  comment:               { fg: RGBA.fromHex("#8b949e"), italic: true },
  number:                { fg: RGBA.fromHex("#79c0ff") },
  boolean:               { fg: RGBA.fromHex("#79c0ff") },
  constant:              { fg: RGBA.fromHex("#79c0ff") },
  function:              { fg: RGBA.fromHex("#d2a8ff") },
  "function.call":        { fg: RGBA.fromHex("#d2a8ff") },
  "function.method.call": { fg: RGBA.fromHex("#d2a8ff") },
  type:                  { fg: RGBA.fromHex("#ffa657") },
  constructor:           { fg: RGBA.fromHex("#ffa657") },
  variable:              { fg: RGBA.fromHex("#e6edf3") },
  "variable.member":     { fg: RGBA.fromHex("#79c0ff") },
  property:              { fg: RGBA.fromHex("#79c0ff") },
  operator:              { fg: RGBA.fromHex("#ff7b72") },
  punctuation:           { fg: RGBA.fromHex("#f0f6fc") },
  "punctuation.bracket": { fg: RGBA.fromHex("#f0f6fc") },
  "punctuation.delimiter": { fg: RGBA.fromHex("#c9d1d9") },

  default:               { fg: RGBA.fromHex("#e6edf3") },
});
